### ISSUE TITLE
Unused code

### ISSUE THREAD

**Issue by denispeplin** [fabrik42/writing_an_interpreter_in_elixir#3]
Elixir compiler complains about unused variable `@types`: https://github.com/fabrik42/writing_an_interpreter_in_elixir/blob/master/lib/monkey/token.ex#L13

If I remove it, no failing tests appear, so looks like compiler isn't wrong about this variable.

**Comment by fabrik42** [comment]
Hi!
You are right, at the moment this variable is there for documentation purposes only, as it lists all possible types that are supported for a token.

I wanted to use it either in a helper method for token creation or in Typespecs or Dialyzer checks, to make sure there are no tokens with invalid type created.

But this didn't happen yet. I am open for any idea that makes better use of this information.

**Comment by denispeplin** [comment]
Maybe this way: #4 ?
I don't know how to enforce using Token.new instead of `%Token{}`, but at least I've used it for existing code, and it will raise when somebody create token with wrong type.
Also with Token.new default literal can be used, `!=` for `not_eq` and so on.

**Comment by denispeplin** [comment]
I've also found that there is no way currently to enforce usage of Token.new: https://groups.google.com/forum/#!topic/elixir-lang-core/hD7SfUaXxFI

**Comment by fabrik42** [comment]
Let's continue the discussion in https://github.com/fabrik42/writing_an_interpreter_in_elixir/pull/4 :)
