### ISSUE TITLE
Is this borrowable?

### ISSUE THREAD

**Issue by jonasbadstuebner** [fabrik42/writing_an_interpreter_in_elixir#7]
Hey there,

I am currently going to implement an interpreter for [DreamBerd](https://github.com/TodePond/DreamBerd).
Can I use your work - with credits of course - and adapt this interpreter to interpret the perfect programming language?
Would also push back improvements, if I can make out any.

Best regards!

**Comment by fabrik42** [comment]
Hi Jonas,
thank you for asking, I appreciate it!

I am absolutely fine with you borrowing parts of this interpreter for your project!
Giving credits would be cool!

Feel free to keep me updated on your efforts, I am curious! 😊

Cheers,
Christian

**Comment by jonasbadstuebner** [comment]
Hi Christian,

thank you for the quick response. And especially for allowing me to use your work as a starting point for this interpreter!
I'm going to update you on my progress!

Greetings,
Jonas

**Comment by fabrik42** [comment]
Awesome - Good luck!
